### ISSUE TITLE
Create port input and output sub-headings

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/hpsf#145]
It might be a good change for HPSF to provide groupings for inputs and outputs under ports to reduce the need for comments. The direction could be inferred based on the grouping to reduce duplication too.

Maybe something like:

```yaml
ports:
  inputs:
  - name: Traces
    type: OTelTraces
  - name: Logs
    type: OTelLogs
  outputs:
  - name: Events
    direction: output
    type: HoneycombEvents
```

_Originally posted by @MikeGoldsmith in https://github.com/honeycombio/hpsf/issues/144#issuecomment-2984670567_
